version: '3.8'

services:
  my-react-app:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      - my-react-app

